releases:
  # https://github.com/helm/charts/tree/master/stable/efs-provisioner
  - name: efs-provisioner
    namespace: kube-system
    chart: stable/efs-provisioner
    values:
      - efsProvisioner:
          efsFileSystemId: {{ requiredEnv "efs_provisoner_file_system_id" }}
          awsRegion: {{ requiredEnv "AWS_DEFAULT_REGION" }}
          path: /
          storageClass:
            name: efs
            isDefault: true
