kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-home
  namespace: hello
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default
